-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 18:45:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mamie_clafoutie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mamie_clafoutie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mamie_clafoutie` DEFAULT CHARACTER SET utf8 ;
USE `mamie_clafoutie` ;

-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`categorie` (
  `id_categorie` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table fonction employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table fonction employe` (
  `id_fonc` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_fonc`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table employe` (
  `id_emp` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `adresse` VARCHAR(45) NULL DEFAULT NULL,
  `table fonction employe_id_fonc` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `valide` TINYINT NULL,
  PRIMARY KEY (`id_emp`),
  INDEX `fk_table employe_table fonction employe_idx` (`table fonction employe_id_fonc` ASC),
  CONSTRAINT `fk_table employe_table fonction employe`
    FOREIGN KEY (`table fonction employe_id_fonc`)
    REFERENCES `mamie_clafoutie`.`table fonction employe` (`id_fonc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table commande` (
  `id_commande` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `fk id employe` INT(11) NOT NULL,
  PRIMARY KEY (`id_commande`),
  INDEX `fk nom employe_idx` (`fk id employe` ASC),
  CONSTRAINT `fk id employe`
    FOREIGN KEY (`fk id employe`)
    REFERENCES `mamie_clafoutie`.`table employe` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table recette` (
  `id_recette` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_recette`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table produit` (
  `id_produit` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prix` DOUBLE NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `categorie_id_categorie` INT(11) NOT NULL,
  `table recette_id_recette` INT(11) NOT NULL,
  PRIMARY KEY (`id_produit`),
  INDEX `fk_table produit_categorie1_idx` (`categorie_id_categorie` ASC),
  INDEX `fk_table produit_table recette1_idx` (`table recette_id_recette` ASC),
  CONSTRAINT `fk_table produit_categorie1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `mamie_clafoutie`.`categorie` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table produit_table recette1`
    FOREIGN KEY (`table recette_id_recette`)
    REFERENCES `mamie_clafoutie`.`table recette` (`id_recette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`ligne de commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`ligne de commande` (
  `quantite` INT(11) NULL DEFAULT NULL,
  `fk id produit` INT(11) NOT NULL,
  `fk id commande` INT(11) NOT NULL,
  INDEX `fk id produit _idx` (`fk id produit` ASC),
  INDEX `fk id commande_idx` (`fk id commande` ASC),
  CONSTRAINT `fk id commande`
    FOREIGN KEY (`fk id commande`)
    REFERENCES `mamie_clafoutie`.`table commande` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk id produit `
    FOREIGN KEY (`fk id produit`)
    REFERENCES `mamie_clafoutie`.`table produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table ingredient` (
  `id_ingredient` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ingredient`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table compose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table compose` (
  `quantite` INT(11) NULL DEFAULT NULL,
  `table recette_id_recette` INT(11) NOT NULL,
  `table ingredient_id_ingredient` INT(11) NOT NULL,
  INDEX `fk_table compose_table recette1_idx` (`table recette_id_recette` ASC),
  INDEX `fk_table compose_table ingredient1_idx` (`table ingredient_id_ingredient` ASC),
  CONSTRAINT `fk_table compose_table ingredient1`
    FOREIGN KEY (`table ingredient_id_ingredient`)
    REFERENCES `mamie_clafoutie`.`table ingredient` (`id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table compose_table recette1`
    FOREIGN KEY (`table recette_id_recette`)
    REFERENCES `mamie_clafoutie`.`table recette` (`id_recette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table vente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table vente` (
  `id_ord` INT(11) NOT NULL AUTO_INCREMENT,
  `quantite total` VARCHAR(45) NULL DEFAULT NULL,
  `quantite restante` INT(11) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `science` VARCHAR(45) NULL DEFAULT NULL,
  `table employe_id_emp` INT(11) NOT NULL,
  `table produit_id_produit` INT(11) NOT NULL,
  PRIMARY KEY (`id_ord`),
  INDEX `fk_table vente_table employe1_idx` (`table employe_id_emp` ASC),
  INDEX `fk_table vente_table produit1_idx` (`table produit_id_produit` ASC),
  CONSTRAINT `fk_table vente_table employe1`
    FOREIGN KEY (`table employe_id_emp`)
    REFERENCES `mamie_clafoutie`.`table employe` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table vente_table produit1`
    FOREIGN KEY (`table produit_id_produit`)
    REFERENCES `mamie_clafoutie`.`table produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamie_clafoutie`.`table employe_has_table vente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamie_clafoutie`.`table employe_has_table vente` (
  `table employe_id_emp` INT(11) NOT NULL,
  `table vente_ord_id` INT(11) NOT NULL,
  PRIMARY KEY (`table employe_id_emp`, `table vente_ord_id`),
  INDEX `fk_table employe_has_table vente_table vente1_idx` (`table vente_ord_id` ASC),
  INDEX `fk_table employe_has_table vente_table employe1_idx` (`table employe_id_emp` ASC),
  CONSTRAINT `fk_table employe_has_table vente_table employe1`
    FOREIGN KEY (`table employe_id_emp`)
    REFERENCES `mamie_clafoutie`.`table employe` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table employe_has_table vente_table vente1`
    FOREIGN KEY (`table vente_ord_id`)
    REFERENCES `mamie_clafoutie`.`table vente` (`id_ord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
